nome = input("Digite o seu nome completo: ")
print("Seu nome em maiúsculas: {}".format(nome.upper()))
print("Seu nome em minúsculas: {}".format(nome.lower()))
print("Seu nome ao todo tem {} letras".format(len(nome)-nome.count(' ')))
print("Seu primeiro nome é {} e ele tem {} letras".format(nome.split()[0],len(nome.split()[0])))
