nome = input("Informe seu nome: ")
nome = nome.lower().strip()
print("A letra A apareceu {} vezes na frase.".format(nome.count('a')))
print("A primeira letra apareceu na posição {}".format(nome.find('a')+1))
print("A última letra apareceu na posição {}".format(nome.rfind('a')+1))
